// ============================================
// 📝 SIGNUP ENDPOINT - Matches user table attributes
// ============================================

router.post('/signup', async (req, res) => {
    try {
        const { username, password } = req.body;
        
        console.log('=================================');
        console.log('📝 Signup attempt for:', username);
        
        // Validate required fields
        if (!username || !password) {
            return res.status(400).json({ error: 'Username and password are required' });
        }
        
        // Validate username length
        if (username.length < 3) {
            return res.status(400).json({ error: 'Username must be at least 3 characters' });
        }
        
        // Validate password length
        if (password.length < 4) {
            return res.status(400).json({ error: 'Password must be at least 4 characters' });
        }
        
        // Check if username already exists
        const existingUser = await User.findOne({ username });
        if (existingUser) {
            console.log('❌ Username already taken:', username);
            return res.status(400).json({ error: 'Username already taken' });
        }
        
        // Get next user_id
        const lastUser = await User.findOne().sort({ user_id: -1 });
        const nextId = lastUser ? lastUser.user_id + 1 : 3;
        console.log(`Next user_id will be: ${nextId}`);
        
        // Create new user (only username, password, role)
        // createdAt and updatedAt will be auto-generated by timestamps
        const newUser = new User({
            user_id: nextId,
            username: username,
            password: password,  // Will be hashed by pre-save hook
            role: 'user'
        });
        
        await newUser.save();
        
        console.log('✅ New user created successfully!');
        console.log(`   Username: ${username}`);
        console.log(`   User ID: ${nextId}`);
        console.log(`   Role: user`);
        console.log(`   Created: ${newUser.createdAt}`);
        console.log('=================================');
        
        res.status(201).json({
            success: true,
            message: 'Account created successfully! You can now login.',
            user: {
                user_id: newUser.user_id,
                username: newUser.username,
                role: newUser.role,
                createdAt: newUser.createdAt,
                updatedAt: newUser.updatedAt
            }
        });
        
    } catch (error) {
        console.error('❌ Signup error:', error);
        res.status(500).json({ error: 'Server error during signup: ' + error.message });
    }
});
